-- Starter taxonomy only. Does not modify companies, claims or tag assignments.
-- Repeatable: existing tags and administrator decisions are preserved.
BEGIN;
INSERT INTO public.directory_tag_groups(key, label, display_order, is_core, filter_enabled) VALUES
  ('services', 'Services', 0, true, true),
  ('pathways', 'Pathways', 1, true, true),
  ('player_level', 'Current player level', 2, false, true),
  ('age_group', 'Age groups served', 3, false, true),
  ('regions', 'Regions served', 4, false, true),
  ('languages', 'Languages', 5, false, true),
  ('price_range', 'Typical engagement price', 6, false, false)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.directory_tags(id, group_key, slug, label, parent_id, display_order, is_active) VALUES
  ('services:advisor', 'services', 'advisor', 'Hockey advising', NULL, 0, true),
  ('services:agent', 'services', 'agent', 'Agent representation', NULL, 1, true),
  ('services:scouting', 'services', 'scouting', 'Scouting & player evaluation', NULL, 2, true),
  ('services:video', 'services', 'video', 'Video analysis', NULL, 3, true),
  ('services:recruiting', 'services', 'recruiting', 'Recruiting & placement', NULL, 4, true),
  ('services:skills-coaching', 'services', 'skills-coaching', 'Skills coaching', NULL, 5, true),
  ('pathways:prep-school', 'pathways', 'prep-school', 'Prep school', NULL, 0, true),
  ('pathways:junior', 'pathways', 'junior', 'Junior hockey', NULL, 1, true),
  ('pathways:ncaa', 'pathways', 'ncaa', 'NCAA', NULL, 2, true),
  ('pathways:u-sports', 'pathways', 'u-sports', 'U SPORTS', NULL, 3, true),
  ('pathways:professional', 'pathways', 'professional', 'Professional hockey', NULL, 4, true),
  ('player_level:aa', 'player_level', 'aa', 'AA', NULL, 0, true),
  ('player_level:aaa', 'player_level', 'aaa', 'AAA', NULL, 1, true),
  ('player_level:prep-high-school', 'player_level', 'prep-high-school', 'Prep / high school', NULL, 2, true),
  ('player_level:junior', 'player_level', 'junior', 'Junior', NULL, 3, true),
  ('player_level:college-university', 'player_level', 'college-university', 'College / university', NULL, 4, true),
  ('player_level:professional', 'player_level', 'professional', 'Professional', NULL, 5, true),
  ('age_group:13-14', 'age_group', '13-14', '13–14', NULL, 0, true),
  ('age_group:15-17', 'age_group', '15-17', '15–17', NULL, 1, true),
  ('age_group:18-20', 'age_group', '18-20', '18–20', NULL, 2, true),
  ('age_group:21-plus', 'age_group', '21-plus', '21 and older', NULL, 3, true),
  ('regions:ca', 'regions', 'ca', 'Canada', NULL, 0, true),
  ('regions:us', 'regions', 'us', 'United States', NULL, 1, true),
  ('regions:ca-ab', 'regions', 'ca-ab', 'Alberta', 'regions:ca', 2, true),
  ('regions:ca-bc', 'regions', 'ca-bc', 'British Columbia', 'regions:ca', 3, true),
  ('regions:ca-mb', 'regions', 'ca-mb', 'Manitoba', 'regions:ca', 4, true),
  ('regions:ca-nb', 'regions', 'ca-nb', 'New Brunswick', 'regions:ca', 5, true),
  ('regions:ca-nl', 'regions', 'ca-nl', 'Newfoundland and Labrador', 'regions:ca', 6, true),
  ('regions:ca-nt', 'regions', 'ca-nt', 'Northwest Territories', 'regions:ca', 7, true),
  ('regions:ca-ns', 'regions', 'ca-ns', 'Nova Scotia', 'regions:ca', 8, true),
  ('regions:ca-nu', 'regions', 'ca-nu', 'Nunavut', 'regions:ca', 9, true),
  ('regions:ca-on', 'regions', 'ca-on', 'Ontario', 'regions:ca', 10, true),
  ('regions:ca-pe', 'regions', 'ca-pe', 'Prince Edward Island', 'regions:ca', 11, true),
  ('regions:ca-qc', 'regions', 'ca-qc', 'Quebec', 'regions:ca', 12, true),
  ('regions:ca-sk', 'regions', 'ca-sk', 'Saskatchewan', 'regions:ca', 13, true),
  ('regions:ca-yt', 'regions', 'ca-yt', 'Yukon', 'regions:ca', 14, true),
  ('regions:us-al', 'regions', 'us-al', 'Alabama', 'regions:us', 15, true),
  ('regions:us-ak', 'regions', 'us-ak', 'Alaska', 'regions:us', 16, true),
  ('regions:us-az', 'regions', 'us-az', 'Arizona', 'regions:us', 17, true),
  ('regions:us-ar', 'regions', 'us-ar', 'Arkansas', 'regions:us', 18, true),
  ('regions:us-ca', 'regions', 'us-ca', 'California', 'regions:us', 19, true),
  ('regions:us-co', 'regions', 'us-co', 'Colorado', 'regions:us', 20, true),
  ('regions:us-ct', 'regions', 'us-ct', 'Connecticut', 'regions:us', 21, true),
  ('regions:us-de', 'regions', 'us-de', 'Delaware', 'regions:us', 22, true),
  ('regions:us-fl', 'regions', 'us-fl', 'Florida', 'regions:us', 23, true),
  ('regions:us-ga', 'regions', 'us-ga', 'Georgia', 'regions:us', 24, true),
  ('regions:us-hi', 'regions', 'us-hi', 'Hawaii', 'regions:us', 25, true),
  ('regions:us-id', 'regions', 'us-id', 'Idaho', 'regions:us', 26, true),
  ('regions:us-il', 'regions', 'us-il', 'Illinois', 'regions:us', 27, true),
  ('regions:us-in', 'regions', 'us-in', 'Indiana', 'regions:us', 28, true),
  ('regions:us-ia', 'regions', 'us-ia', 'Iowa', 'regions:us', 29, true),
  ('regions:us-ks', 'regions', 'us-ks', 'Kansas', 'regions:us', 30, true),
  ('regions:us-ky', 'regions', 'us-ky', 'Kentucky', 'regions:us', 31, true),
  ('regions:us-la', 'regions', 'us-la', 'Louisiana', 'regions:us', 32, true),
  ('regions:us-me', 'regions', 'us-me', 'Maine', 'regions:us', 33, true),
  ('regions:us-md', 'regions', 'us-md', 'Maryland', 'regions:us', 34, true),
  ('regions:us-ma', 'regions', 'us-ma', 'Massachusetts', 'regions:us', 35, true),
  ('regions:us-mi', 'regions', 'us-mi', 'Michigan', 'regions:us', 36, true),
  ('regions:us-mn', 'regions', 'us-mn', 'Minnesota', 'regions:us', 37, true),
  ('regions:us-ms', 'regions', 'us-ms', 'Mississippi', 'regions:us', 38, true),
  ('regions:us-mo', 'regions', 'us-mo', 'Missouri', 'regions:us', 39, true),
  ('regions:us-mt', 'regions', 'us-mt', 'Montana', 'regions:us', 40, true),
  ('regions:us-ne', 'regions', 'us-ne', 'Nebraska', 'regions:us', 41, true),
  ('regions:us-nv', 'regions', 'us-nv', 'Nevada', 'regions:us', 42, true),
  ('regions:us-nh', 'regions', 'us-nh', 'New Hampshire', 'regions:us', 43, true),
  ('regions:us-nj', 'regions', 'us-nj', 'New Jersey', 'regions:us', 44, true),
  ('regions:us-nm', 'regions', 'us-nm', 'New Mexico', 'regions:us', 45, true),
  ('regions:us-ny', 'regions', 'us-ny', 'New York', 'regions:us', 46, true),
  ('regions:us-nc', 'regions', 'us-nc', 'North Carolina', 'regions:us', 47, true),
  ('regions:us-nd', 'regions', 'us-nd', 'North Dakota', 'regions:us', 48, true),
  ('regions:us-oh', 'regions', 'us-oh', 'Ohio', 'regions:us', 49, true),
  ('regions:us-ok', 'regions', 'us-ok', 'Oklahoma', 'regions:us', 50, true),
  ('regions:us-or', 'regions', 'us-or', 'Oregon', 'regions:us', 51, true),
  ('regions:us-pa', 'regions', 'us-pa', 'Pennsylvania', 'regions:us', 52, true),
  ('regions:us-ri', 'regions', 'us-ri', 'Rhode Island', 'regions:us', 53, true),
  ('regions:us-sc', 'regions', 'us-sc', 'South Carolina', 'regions:us', 54, true),
  ('regions:us-sd', 'regions', 'us-sd', 'South Dakota', 'regions:us', 55, true),
  ('regions:us-tn', 'regions', 'us-tn', 'Tennessee', 'regions:us', 56, true),
  ('regions:us-tx', 'regions', 'us-tx', 'Texas', 'regions:us', 57, true),
  ('regions:us-ut', 'regions', 'us-ut', 'Utah', 'regions:us', 58, true),
  ('regions:us-vt', 'regions', 'us-vt', 'Vermont', 'regions:us', 59, true),
  ('regions:us-va', 'regions', 'us-va', 'Virginia', 'regions:us', 60, true),
  ('regions:us-wa', 'regions', 'us-wa', 'Washington', 'regions:us', 61, true),
  ('regions:us-wv', 'regions', 'us-wv', 'West Virginia', 'regions:us', 62, true),
  ('regions:us-wi', 'regions', 'us-wi', 'Wisconsin', 'regions:us', 63, true),
  ('regions:us-wy', 'regions', 'us-wy', 'Wyoming', 'regions:us', 64, true),
  ('languages:english', 'languages', 'english', 'English', NULL, 0, true),
  ('languages:french', 'languages', 'french', 'French', NULL, 1, true),
  ('price_range:under-1000', 'price_range', 'under-1000', 'Under $1,000', NULL, 0, true),
  ('price_range:1000-2499', 'price_range', '1000-2499', '$1,000–$2,499', NULL, 1, true),
  ('price_range:2500-4999', 'price_range', '2500-4999', '$2,500–$4,999', NULL, 2, true),
  ('price_range:5000-9999', 'price_range', '5000-9999', '$5,000–$9,999', NULL, 3, true),
  ('price_range:10000-plus', 'price_range', '10000-plus', '$10,000+', NULL, 4, true)
ON CONFLICT (id) DO NOTHING;
COMMIT;
