import { readFileSync } from 'node:fs'
import { randomUUID } from 'node:crypto'
import { parse } from 'dotenv'
import { createClient } from '@supabase/supabase-js'

const env = parse(readFileSync('.env.local'))
const base = 'http://127.0.0.1:3001'
const db = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY)
const { data: company, error } = await db.from('companies').select('id').eq('slug', '2112-hockey-agency').single()
if (error) throw new Error('Could not resolve verification listing')
const ids = [randomUUID(), randomUUID()]
const headers = { Origin: base, Referer: base + '/listings/2112-hockey-agency?verification=1', 'Content-Type': 'application/json' }
try {
  const send = (id, type) => fetch(`${base}/api/advisors/${company.id}/track-click`, {
    method: 'POST', headers, body: JSON.stringify({ click_type: type, event_id: id, analytics_consent: true, referrer: 'https://example.com/analytics-verification?omit=this' }),
  })
  for (const [id, type] of [[ids[0], 'profile_view'], [ids[0], 'profile_view'], [ids[1], 'website']]) {
    const response = await send(id, type)
    if (!response.ok) throw new Error(`Local event endpoint returned ${response.status}`)
  }
  const { data, error: readError } = await db.from('directory_events').select('id,event_type,metadata,referrer').in('id', ids)
  if (readError || data.length !== 2) throw new Error('Persistence or retry deduplication failed')
  if (data.some(row => row.metadata.environment !== 'development' || row.referrer !== 'https://example.com/analytics-verification' || row.metadata.page_url.includes('?'))) throw new Error('Environment separation or URL sanitization failed')
  console.log(JSON.stringify({ saved: data.length, duplicateRetryCounted: false, environment: 'development', events: data.map(row => row.event_type), sanitized: true }))
} finally {
  // Remove only the disposable IDs generated by this verification run.
  const { error: cleanupError } = await db.from('directory_events').delete().in('id', ids)
  if (cleanupError) throw new Error('Verification events need cleanup: ' + ids.join(', '))
  console.log('Verification events removed.')
}
